In [1]:
folder_name = 'data/'
stock_name = 'AAPL'

In [2]:
from test import get_data

In [3]:
help(get_data)

Help on function get_data in module test:

get_data(folder_name, stock_name)

In [4]:
get_data(folder_name, stock_name)

,Date,Open,High,Low,Close,Volume,Ex-Dividend,Split Ratio,Adj. Open,Adj. High,Adj. Low,Adj. Close,Adj. Volume
0,2007-12-03,181.86,184.14,177.70,178.8600,34338200.0,0.0,1.0,23.371545,23.664556,22.836927,22.986003,240367400.0
1,2007-12-04,177.15,180.90,176.99,179.8100,27635700.0,0.0,1.0,22.766244,23.248171,22.745682,23.108091,193449900.0
2,2007-12-05,182.89,186.00,182.41,185.5000,31871500.0,0.0,1.0,23.503914,23.903592,23.442227,23.839335,223100500.0
3,2007-12-06,186.19,190.10,186.12,189.9528,32136100.0,0.0,1.0,23.928010,24.430500,23.919014,24.411582,224952700.0
4,2007-12-07,190.54,194.99,188.04,194.3000,38073800.0,0.0,1.0,24.487046,25.058933,24.165761,24.970258,266516600.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2512,2017-11-27,175.05,175.08,173.34,174.0900,20536313.0,0.0,1.0,175.050000,175.080000,173.340000,174.090000,20536313.0
2513,2017-11-28,174.30,174.87,171.86,173.0700,25468442.0,0.0,1.0,174.300000,174.870000,171.860000,173.070000,25468442.0
2514,2017-11-29,172.63,172.92,167.16,169.4800,40788324.0,0.0,1.0,172.630000,172.920000,167.160000,169.480000,40788324.0
2515,2017-11-30,170.43,172.14,168.44,171.8500,40172368.0,0.0,1.0,170.430000,172.140000,168.440000,171.850000,40172368.0
2516,2017-12-01,169.95,171.67,168.50,171.0500,39590080.0,0.0,1.0,169.950000,171.670000,168.500000,171.050000,39590080.0

In [5]:
a